on: push
name: larv
jobs:
  phpunit:
    runs-on: ubuntu-latest
    container:
      image: kirschbaumdevelopment/laravel-test-runner:8.2
 
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
 
    - name: Install composer dependencies
      run: |
        sudo chmod -R 755 bootstrap/cache/
        composer update
        composer install --no-scripts
 
    - name: Prepare Laravel Application
      run: |
        cp .env.larv .env
        php artisan key:generate
 
    - name: Run Testsuite
      run: vendor/bin/phpunit tests/